# Generated by Django 3.2.7 on 2021-10-14 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_tipo')),
                ('nombre', models.CharField(max_length=30, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id_inmueble')),
                ('precio', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('disponible', models.BooleanField(default=False)),
                ('id_arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_inmueble_arrendatario', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_inmueble_tipoinmueble', to='authApp.tipoinmueble')),
            ],
        ),
    ]
