# Generated by Django 3.2.7 on 2021-10-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_inmueble_tipoinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fechaCreacion',
            field=models.DateField(default='1995-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Inmueble_arrendado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_inmueble_arrendado', to=settings.AUTH_USER_MODEL)),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_inmueble', to='authApp.inmueble')),
            ],
        ),
    ]
